data:
  input: './data_for_inference/sample_test/input.json' 
  pred_output: './data_for_inference/sample_test/predictions.json'
  pred_images_output: './data_for_inference/sample_test/output_pr_images/'
model:
  rudolph:
    name: '1.3B'
    fp16: true
    device: 'cuda'
    cache_dir: '/tmp/rudolph'
    pretrained: False
  rudolph_weight: './checkpoints_6tasks_rudolph-1_3b-v1/last.ckpt' 
  vae:
    dwt: false
    device: 'cuda'
  params:
    num_layers: 24
    hidden_size: 2048
    num_attention_heads: 16
    embedding_dropout_prob: 0.1
    output_dropout_prob: 0.1
    attention_dropout_prob: 0.1
    l_text_seq_length: 128
    image_tokens_per_dim: 32
    r_text_seq_length: 128
    kernel_size: 9
    last_kernel_size: 11
    cogview_sandwich_layernorm: True
    cogview_pb_relax: True
    text_special_tokens: 2048
    image_special_tokens: 64
    vocab_size: 16512
    image_vocab_size: 8192
    mlp_activation: "gelu_jit"
  bs: 16