data:
  input: './data_for_inference/sample_test/input.json' 
  pred_output: './data_for_inference/sample_test/predictions.json'
  pred_images_output: './data_for_inference/sample_test/output_pr_images/'
model:
  rudolph:
    name: '2.7B'
    fp16: true
    device: 'cuda'
    cache_dir: '/tmp/rudolph'
    pretrained: False
  rudolph_weight: './checkpoints_6tasks_rudolph-2_7b-v4/last.ckpt' 
  vae:
    dwt: false
    device: 'cuda'
  params:
    num_layers: 32
    hidden_size: 2560
    num_attention_heads: 32
    embedding_dropout_prob: 0.1
    output_dropout_prob: 0.1
    attention_dropout_prob: 0.1
    l_text_seq_length: 384
    image_tokens_per_dim: 24
    r_text_seq_length: 128
    kernel_size: 7
    last_kernel_size: 9
    cogview_sandwich_layernorm: true
    cogview_pb_relax: true
    text_special_tokens: 1024
    image_special_tokens: 1024
    vocab_size: 16768
    image_vocab_size: 8192
    mlp_activation: "gelu_jit"
  bs: 26