data:
  input: './data_for_inference/public_test/input.json' 
  pred_output: './data_for_inference/public_test/predictions.json'
  pred_images_output: './data_for_inference/public_test/output_pr_images/'
model:
  rudolph:
    name: '350M'
    fp16: true
    device: 'cuda:1'
    cache_dir: '/tmp/rudolph'
    pretrained: False
  rudolph_weight: './checkpoints_6tasks_rudolph-350m-v6/light_last.pt' 
  vae:
    dwt: false
    device: 'cuda:1'
  params:
    num_layers: 24
    hidden_size: 1024
    num_attention_heads: 16
    embedding_dropout_prob: 0.1
    output_dropout_prob: 0.1
    attention_dropout_prob: 0.1
    l_text_seq_length: 64
    image_tokens_per_dim: 16
    r_text_seq_length: 64
    kernel_size: 7
    last_kernel_size: 9
    cogview_sandwich_layernorm: true
    cogview_pb_relax: true
    text_special_tokens: 384
    image_special_tokens: 384
    vocab_size: 16448
    image_vocab_size: 8192
    mlp_activation: "gelu_jit"
  bs: 50